# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mind of JC
email: jcheong[dot]GR[at]dartmouth[dot]edu
description: > # this means to ignore newlines until "baseurl:"
  I am a graduate student at Psychological and Brain Sciences at
  Dartmouth College. This is a blog for my work and random digressions. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jcheong0428
github_username:  jcheong0428
instagram_username: real_sage
# Build settings
markdown: kramdown
